DEFAULT_SAMPLE_RATE = 16000

SUPPORTED_AUDIO_FORMATS = [".wav", ".mp3", ".m4a"]
SUPPORTED_VIDEO_FORMATS = [".mp4", ".mov"]
SUPPORTED_MEDIA_FORMATS = SUPPORTED_AUDIO_FORMATS + SUPPORTED_VIDEO_FORMATS

MIN_DURATION_SECONDS = 3.0

LOW_RMS_THRESHOLD = 0.005

MAX_FILE_SIZE_MB = 50
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024
